version: "3"
services:
  node-server: 
    build: 
        context: .
        args: 
          NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=ramanda
      - MONGO_PASSWORD=ramanda123
    command: npm run dev
    # env_file:
    #   - fileName